### ISSUE TITLE
PWPush.com "Copy to Clipboard" adding trailing spaces on Firefox

### ISSUE THREAD

**Issue by CtrlAlteSKa** [pglombardo/PasswordPusher#189]
Hi, we've been using pwpush.com to send across passwords in bulk to our users. In the last few on-boarding projects, users have reported their passwords from the pwpush links to not work for them. 
We've now investigated this issue and have found that pwpush adds a trailing space both before and after the copied password when the "Copy to Clipboard" button is used, causing the user logon to fail. Tests on Chrome and Edge browsers did not reproduce this same issue.

**Comment by pglombardo** [comment]
Hi @CtrlAlteSKa - I had another report of this on FirefoxESR-68.12.0-it.  It was fixed by updating to the latest Firefox.  Could you give that at try to at least confirm that it resolves the issue?

The original issue reported was https://github.com/pglombardo/PasswordPusher/issues/185

**Comment by greecemunky** [comment]
Running on Firefox 88.0.1 (current latest), there are both leading and trailing spaces when using the "Copy to Clipboard" button.  Additionally, when highlighting the on-screen password to manually copy, a trailing space is selected and copied.  This was initially confirmed in Firefox 88.0.

Trailing whitespace also appears in Edge 18.18363 (old, I know) when using the "Copy to Clipboard" button.

I can confirm "Copy to Clipboard" works OK in Chrome 90.0.4430.212 and Edge 91.0.864.37.  The on-screen password also highlights correctly, with no trailing space.

**Comment by CtrlAlteSKa** [comment]
Hi @pglombardo , @greecemunky 

I can confirm that this issue persists and is still happening on Firefox 88.0.1 (64-bit)

**Comment by pglombardo** [comment]
Ok thanks for the info all. I'll investigate and figure it out this week.

**Comment by CtrlAlteSKa** [comment]
@pglombardo I can confirm that the issue is now fixed on my Firefox 88.0.1 (64-bit).
Thank you very much for the fix!
