### ISSUE TITLE
API returns internal server error when processing passwords containing £ symbol

### ISSUE THREAD

**Issue by davidshomelab** [pglombardo/PasswordPusher#204]
### Steps to replicate:

```
$Request = [PSCustomObject]@{ 
payload = "£" 
expire_after_days = 5
expire_after_views = 5
 }

Invoke-RestMethod -Method "Post" -Uri "https://pwpush.com/p.json" -ContentType "application/json" -TimeoutSec 5 -Body ([PSCustomObject]@{     
 password = $Request      
 } | ConvertTo-Json )
```
**Output:**
`Invoke-RestMethod: {"status":500,"error":"Internal Server Error"}`

### Working Example:

```
$Request = [PSCustomObject]@{ 
payload = "a" 
expire_after_days = 5
expire_after_views = 5
 }

Invoke-RestMethod -Method "Post" -Uri "https://pwpush.com/p.json" -ContentType "application/json" -TimeoutSec 5 -Body ([PSCustomObject]@{     
 password = $Request      
 } | ConvertTo-Json )
```
**Output:**
```
id                  : 1246972
payload             : a
expire_after_days   : 5
expire_after_views  : 5
expired             : False
url_token           : oenieuhhgb5t6ge3
created_at          : 31/07/2021 18:36:11
updated_at          : 31/07/2021 18:36:11
user_id             : 
deleted             : False
first_view          : False
deletable_by_viewer : True
days_remaining      : 5
views_remaining     : 5
```
Passwords containing the £ symbol are accepted when processing via the web interface

### Edit
after further testing it appears that the ¬ symbol is also affected

**Comment by pglombardo** [comment]
Thanks for filing with all the details.  I believe those are valid ASCII characters (not multibyte unicode) so I'm at a loss.  I'll add some tests to the test suite to investigate and post back soon.

**Comment by pglombardo** [comment]
Fix pending release: https://github.com/pglombardo/PasswordPusher/pull/205

**Comment by pglombardo** [comment]
@davidshomelab this has been fixed on Github master branch and in the docker containers.  I expect pwpush.com to be updated by this weekend when I release a theme redesign.  (I avoid mid-week deploys to lessen user interruptions) Thanks for the very helpful report!

**Comment by pglombardo** [comment]
This fix is live on pwpush.com now.  (っ＾▿＾)۶🍸🌟🍺٩(˘◡˘ )

**Comment by davidshomelab** [comment]
Thank you :) Seems to work in Python now. Still failing in PowerShell but I assume that's a character encoding thing specific to PowerShell. Will continue to investigate

**Comment by pglombardo** [comment]
Hi @davidshomelab  - Just an update that the API has some cleanup coming.  I'm adding support for `Authorization` headers as well.  It shouldn't break anything but just a heads up.  See #3068 

Hope all is well!
