### ISSUE TITLE
Amend uk locale

### ISSUE THREAD

**Issue by SystemNickDev** [pglombardo/PasswordPusher#3300]
## Checklist

- [x] I've searched the project's [`issues`](https://github.com/pglombardo/PasswordPusher/issues?q=is%3Aissue).
- [x] I've searched the project's [`discussions`](https://github.com/pglombardo/PasswordPusher/discussions).

## ❓ Question

How can I help with amendments to Ukrainian localization?
Is it possible to grant access to [translation.io](https://translation.io/pglombardo/pwpush-oss/uk)?

There are some inconsistent/incorrect/funny strings, which look like auto-translations and should not be present on a resource for sharing confidential information. I would be glad to find free time for some help.

## 📎 Additional context

I use self-hosted OSS version `docker.io/pglombardo/pwpush:latest` for personal use in homelab, but https://pwpush.com/?locale=uk has the same issues.

Some basic examples:

- Your own name in footer is partially translated as "Пітер Giacomo Lombardo"
- Character limit in textbox input translated as "person characters"
- Status text "Copied!" (password was copied) translated as "Understood"
- Other mashups of inappropriate synonyms or completely different meanings

**Comment by pglombardo** [comment]
Hi @SystemNickDev - send me your username on translation.io and I'll add you to the project.  Thanks for offering!

**Comment by SystemNickDev** [comment]
Thanks in advance @pglombardo 
The username is the same: [systemnickdev](https://translation.io/systemnickdev)

**Comment by pglombardo** [comment]
Ok - added you to the project.  You should get the invite soon.  Once you are done, I'll resync the language strings and release.

Heads up that this will update the OSS/self-hosted version only.  pwpush.com is in translation flux right now and needs an updated solution.

**Comment by pglombardo** [comment]
Hi @SystemNickDev - I just pushed out [a new release](https://github.com/pglombardo/PasswordPusher/releases/tag/v1.53.9) with the updated strings you provided - thanks!

**Comment by SystemNickDev** [comment]
Thanks for adding me to the project, but I still have some work to do there.
I started checking all strings from A to Z, there is still ~20% to check at the bottom of the list. Hope it's not a problem to sync the rest later.

I'm not a professional translator or anything, but there was a bunch of common labels I'm confident about. Later when I fully configure my mail server and start using admin panel I might make another adjustments.

**Comment by pglombardo** [comment]
By all means & no problem.   I usually sync and push updated strings once a week.

**Comment by SystemNickDev** [comment]
Well, it was not quick, but I found some time to go through all translations, and now I'm more or less happy with the results.
Will keep an eye on it in the future when new strings are added or when I find mistakes in context.

**Comment by pglombardo** [comment]
Excellent - thanks @SystemNickDev!  I'll sync and release the updated strings for the next release.
